In [1]:
import tensorflow as tf

In [2]:
print(tf.__version__)

1.6.0


In [4]:
hello = tf.constant("Hello ")

In [5]:
world = tf.constant("World")

In [6]:
type(hello)

tensorflow.python.framework.ops.Tensor

In [7]:
print(hello)

Tensor("Const_1:0", shape=(), dtype=string)


In [8]:
with tf.Session() as sess:
    result = sess.run(hello+world)

In [9]:
print(result)

Hello World


In [10]:
a = tf.constant(10)

In [11]:
b = tf.constant(20)

In [12]:
a + b

<tf.Tensor 'add_1:0' shape=() dtype=int32>

In [15]:
with tf.Session() as sess:
    result = sess.run(a+b)

In [16]:
result

30

In [29]:
const = tf.constant(10)

In [30]:
fill_mat = tf.fill((4,4),10)

In [31]:
myzeros = tf.zeros((4,4))

In [32]:
myones = tf.ones((4,4))

In [33]:
myrandn = tf.random_normal((4,4),mean=0,stddev=1.0)

In [34]:
myrandu = tf.random_uniform((4,4),minval=0,maxval=1)

In [35]:
my_ops = [const, fill_mat, myzeros, myones, myrandn, myrandu]

In [36]:
sess = tf.InteractiveSession()

In [39]:
for op in my_ops:
    print(sess.run(op))
    print("\n")
    print(op.eval())
    print("\n")

10


10


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


[[-0.30275226  0.16705255  0.688266    1.0462782 ]
 [ 0.7270683   0.59219825  0.9739306  -1.1417096 ]
 [-0.58723044 -0.9481772   1.2026783  -0.08135188]
 [ 0.09820502 -1.2642485   0.59115225  0.16838466]]


[[-0.7229929   0.07157675  0.24245729 -0.53051037]
 [ 1.250704    0.9706589   0.14766397 -0.3702546 ]
 [-1.0986571   1.3945258  -0.33450013  0.50735456]
 [-0.81365454  0.03015797  0.01384841  0.21444418]]


[[0.6226109  0.31541717 0.5409678  0.22007453]
 [0.88979304 0.6642871  0.08149445 0.6345289 ]
 [0.80058944 0.23139274 0.8717152  0.21042669]
 [0.80783725 0.4838338  0.1691432  0.18673658]]


[[0.480

In [43]:
a = tf.constant([ [1,2],
                [3,4] ])

In [44]:
a.get_shape()

TensorShape([Dimension(2), Dimension(2)])

In [45]:
b = tf.constant([ [10], [100] ])

In [46]:
b.get_shape()

TensorShape([Dimension(2), Dimension(1)])

In [47]:
result = tf.matmul(a,b)

In [48]:
sess.run(result)

array([[210],
       [430]], dtype=int32)

In [49]:
result.eval()

array([[210],
       [430]], dtype=int32)